version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432

  # postgrest:
  #   image: postgrest/postgrest
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 3000:3000
  #   environment:
  #     PGRST_DB_URI: postgres://postgres:example@db:5432/mydatabase
  #     PGRST_DB_SCHEMA: public
  #     PGRST_SERVER_PROXY_URI: http://postgrest:3000
